---
sidebar: sidebar 
permalink: reference-supported-configs.html 
keywords: ec2, instance, type, vm, explore, standard, premium, byol, capacity, maximum, virtual machine, ontap cloud, supported, configurations 
summary: ONTAP Cloud est disponible dans plusieurs configurations dans AWS et Azure. 
---
= Configurations compatibles
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Deux options de tarification sont disponibles dans ONTAP Cloud dans AWS et Azure : le paiement à l'utilisation ou le modèle BYOL (où vous apportez votre propre licence). Le paiement basé sur l'utilisation vous permet de choisir parmi trois configurations : explore, Standard ou Premium.



== ONTAP Cloud pour AWS

Dans AWS, vous pouvez déployer ONTAP Cloud comme un système unique ou une paire HA.

[cols="h,d,d,d,d"]
|===
|  | Découvrir | Standard | Premium | BYOL 


| Types d'instances EC2 | m4.xlarge  a| 
* m4.2xlarge
* r4.xlarge

 a| 
* c4.4xlarge
* c4.8xlarge
* m4,4xlarge
* r4.2xlarge

 a| 
* c4.4xlarge
* c4.8xlarge
* m4.xlarge
* m4.2xlarge
* m4,4xlarge
* r4.xlarge
* r4.2xlarge




| Stockage sous-jacent 4+| SSD à usage générique, SSD IOPS provisionnés, HDD optimisés pour le débit et HDD jusqu'à 16 Tio par disque 


| Limite de capacité de licence | 2 To | 10 To | 368 To | 368 Tio par licence 
|===
Remarques :

. Les configurations avec paiement à l'utilisation ne sont pas prises en charge par GovCloud (USA).
. Lorsque vous choisissez un type d'instance EC2, vous pouvez indiquer s'il s'agit d'une instance partagée ou dédiée.
. Les performances d'écriture améliorées sont prises en charge lorsque les SSD EBS sont utilisés avec ONTAP Cloud Standard, Premium et BYOL.
. Le Tiering des données est pris en charge avec ONTAP Cloud Standard, Premium et BYOL.
. Si vous activez la hiérarchisation des données, la limite de capacité d'un système reste la même. La limite de capacité inclut à la fois les disques et le stockage objet.
. Pour la prise en charge des régions AWS, voir https://bluexp.netapp.com/cloud-volumes-global-regions["Régions Cloud volumes Global"].




== Cloud ONTAP pour Azure

Dans Azure, vous pouvez déployer ONTAP Cloud comme un système à un seul nœud.

[cols="h,d,d,d,d"]
|===
|  | Découvrir | Standard | Premium | BYOL 


| Types de machines virtuelles | DS3_v2  a| 
* DS4_v2
* DS13_v2

 a| 
* DS5_v2
* DS14_v2

 a| 
* DS3_v2
* DS4_v2
* DS5_v2
* DS13_v2
* DS14_v2




| Stockage sous-jacent 4+| Disques gérés HDD standard, disques gérés SSD standard et disques gérés SSD premium, jusqu'à 32 To par disque 


| Limite de capacité de licence | 2 To | 10 To | 368 To | 368 Tio par licence 
|===
Remarques :

. Les performances d'écriture améliorées sont prises en charge avec les disques de stockage Azure Premium avec ONTAP Cloud Standard, Premium et BYOL, mais pas avec le type de machine virtuelle DS3_v2.
. Pour la prise en charge des régions Azure, voir https://bluexp.netapp.com/cloud-volumes-global-regions["Régions Cloud volumes Global"].

